steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/js-classified-server:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/js-classified-server:latest'
      - '.'
    dir: 'server'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/js-classified-server:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/js-classified-server:latest'

  # Deploy to Cloud Run (optional - uncomment if using Cloud Run)
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'js-classified-server'
  #     - '--image'
  #     - 'gcr.io/$PROJECT_ID/js-classified-server:$SHORT_SHA'
  #     - '--region'
  #     - 'us-central1'
  #     - '--platform'
  #     - 'managed'
  #     - '--memory'
  #     - '512Mi'
  #     - '--cpu'
  #     - '1'
  #     - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/js-classified-server:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/js-classified-server:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

