steps:
  # Build the Docker image with cache optimization
  # Build from root directory to access both server/ and db/ directories
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/locful-api:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/locful-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/locful-api:latest'
      - '-f'
      - 'server/Dockerfile'
      - '.'
    # No 'dir' specified - build from repo root

  # Push both tags (they run after build step automatically)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/locful-api:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/locful-api:latest'

  # Deploy to Cloud Run automatically after build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'locful-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/locful-api:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest,CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest,CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest'

images:
  - 'gcr.io/$PROJECT_ID/locful-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/locful-api:latest'

options:
  # Use faster machine type if you have quota (significantly speeds up builds)
  # machineType: 'E2_HIGHCPU_2'  # 2 vCPU - much faster than default
  # machineType: 'E2_HIGHCPU_8'  # 8 vCPU - even faster (if you have quota)
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'  # Reduced from 1200s since builds should be faster now

