export type RewardAction =
  | 'DAILY_LOGIN'
  | 'LISTING_PUBLISHED'
  | 'LISTING_REPUBLISHED'
  | 'PROFILE_COMPLETED'
  | 'LISTING_UNIQUE_VIEW'
  | 'BUYER_FEEDBACK_SUBMITTED'
  | 'BUYER_FEEDBACK_RECEIVED';
